### ISSUE TITLE
2019 March

### ISSUE THREAD

**Issue by The-New-Guy** [INPUG/Meetings#9]
During the **March 2019** user group meeting we will be covering the following topics:

#### Mathias Jessen

Mathias is a Windows-focused Security Engineer by day, and an insatiable PowerShell wonk 24/7

##### I'll do it myself: implementing splatting for .NET methods in 15 minutes or less

Mathias will briefly cover the basics of reflection in .NET and then build and demo a few PowerShell functions live.

## Announcements

- TBA

## Discussion

- After the presentation we will open the meeting up for any discussion topics.

**Comment by IISResetMe** [comment]
Topic title is "I'll do it myself: implementing splatting for .NET methods in 15 minutes or less", will briefly cover the basics of reflection in .NET and then build and demo a few PowerShell functions live

**Comment by The-New-Guy** [comment]
To see more about .NET splatting see here: https://github.com/IISResetMe/dotSplat
